spring:
  profiles:
    active: dev
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

---
#开发环境配置
spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sqsx
      username: root
      password: root

server:
  port: 8080
  context-path: /demodev

---
#测试环境配置
spring:
  profiles: test
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sqsx
      username: root
      password: root

server:
  port: 8081
  context-path: /demotest

---
#生产环境配置
spring:
  profiles: pro
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sqsx
      username: root
      password: root

server:
  port: 8082
  context-path: /demopro



